language: node_js

os:
  - linux
  - windows
  - osx

sudo: false

node_js:
  - node
  - lts/*
  - 10
  - 9
  - 8
  - 7

notifications:
  email: false

cache:
  npm: true

jobs:
  include:
    - stage: test
      script: npm run test

    - stage: release
      script: skip
      deploy:
        skip_cleanup: true
        provider: script
        script:
          - rm -rf index.js test && mv src/* . && rm -rf src
          - ls -lah1
          - npm pack --dry-run
          # - npx semantic-release
