language: node_js

node_js:
  - node

os:
  - linux
  # - osx
  # - windows

sudo: false

notifications:
  email: false

cache:
  npm: true

jobs:
  include:
    - stage: test
      script:
        - npm run test

    - stage: release
      script:
        # restructure the package
        - rm -rf index.js test && mv src/* . && rm -rf src
        # list and show the files that will be released
        - ls -lah1
        - npm pack --dry-run

      deploy:
        skip_cleanup: true
        provider: script
        script:
          # - npx semantic-release
