language: node_js

node_js:
  - node
  # - lts/*
  # - 10
  # - 9
  # - 8
  # - 7

os:
  - linux
  # - osx
  # - windows

sudo: false

notifications:
  email: false

cache:
  npm: true

jobs:
  include:
    - stage: test
      script:
        - npm run test

    - stage: release
      script:
        # restructure the package, then list the files that will be released
        - rm -rf index.js test && mv src/* . && rm -rf src
        - npm pack --dry-run

      deploy:
        skip_cleanup: true
        provider: script
        script:
          # - npx semantic-release
