language: node_js

os:
  - linux
  - windows
  - osx

sudo: false

node_js:
  - node
  - lts/*
  - 10
  - 9
  - 8
  - 7

notifications:
  email: false

cache:
  npm: true
  directories:
    - ./dist

stages:
  - build
  - test
  # - release

jobs:
  include:
    - stage: build
      script: npm run build

    - stage: test
      script: npm run test

    # - stage: release
    #   script: skip
    #   deploy:
    #     skip_cleanup: true
    #     provider: script
    #     script:
    #       - npx semantic-release
